name: Codecov

on:
  push:
    branches:
      - 'master'

jobs:
  codecov-workflow:
    runs-on: ubuntu
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
